### ISSUE TITLE
deploy on vercel?

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [Xenapsis/Xenapsis.github.io#1]
how to deploy on vercel since my school blocks github

**Comment by Grinnny** [comment]
You should deploy the newer version (https://github.com/Xenapsis-dev/Xenapsis-V3-Static or https://github.com/Xenapsis-dev/Xenapsis-V3-Bare but the bare will have to change some things for it to work on the bare.

**Comment by Grinnny** [comment]
The static prob will not have a working proxy.
